# Generated by Django 5.1.6 on 2025-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0003_remove_profile_image_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=1, upload_to='doctorpic'),
        ),
    ]
