# Generated by Django 5.1.6 on 2025-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0008_alter_profile_image_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profilepic/default.jpg', upload_to='profilepic'),
        ),
    ]
