# Generated by Django 5.1.6 on 2025-03-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0010_appointment_age_appointment_gender_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
