# Generated by Django 5.1.6 on 2025-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0011_remove_appointment_age_remove_appointment_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
