# Generated by Django 5.1.6 on 2025-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0012_appointment_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
