# Generated by Django 5.1.6 on 2025-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0014_alter_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
