# Generated by Django 5.1.6 on 2025-03-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0018_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='payment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors_appointment.doctor'),
        ),
    ]
