# Generated by Django 5.1.6 on 2025-03-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0020_payment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fee',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
